import Foundation

/// 시스템 언어에 따른 UI 문자열 (ko, en, ja, zh-Hans, zh-Hant, th, ru, it)
enum L10n {
    enum Key: String {
        case connectedMacs, pauseSync, resumeSync, launchAtLogin, quit
        case loginErrorTitle, loginErrorBody, onlyDuringRemote, showInDock, settings
        case tagline, statusSyncing, statusStandby, statusPaused, dockHint
        case viaLocalNetwork, viaTailscale, viaIncoming, noPeers, statusNotConnected, updateAvailable
        case connectionRequest, connectionRequestBody, approve, reject
        case pairNewMac, pairingCode, pairingHint
        case forgetDevice, resetPairings
        case alwaysTrustDevice, remotePairingChoice, createInvite, enterInvite
        case cancel, nearbyPairing, inviteReady, inviteCopied, enterInviteBody, join, invalidInvite
        case copyInvite, pasteInvite, invitePlaceholder
    }

    private static let lang: String = {
        for preferred in Locale.preferredLanguages {
            let p = preferred.lowercased()
            if p.hasPrefix("ko") { return "ko" }
            if p.hasPrefix("ja") { return "ja" }
            if p.hasPrefix("zh") {
                if p.contains("hant") || p.contains("tw") || p.contains("hk") || p.contains("mo") {
                    return "zh-Hant"
                }
                return "zh-Hans"
            }
            if p.hasPrefix("th") { return "th" }
            if p.hasPrefix("ru") { return "ru" }
            if p.hasPrefix("it") { return "it" }
            if p.hasPrefix("en") { return "en" }
        }
        return "en"
    }()

    static func t(_ key: Key) -> String {
        table[lang]?[key] ?? table["en"]![key]!
    }

    static func connectedMacs(_ count: Int) -> String {
        String(format: t(.connectedMacs), count)
    }

    private static let table: [String: [Key: String]] = [
        "en": [
            .connectionRequest: "HangulSync Connection Request",
            .connectionRequestBody: "%@ wants to sync input sources. Do you trust this connection?",
            .approve: "Approve",
            .reject: "Reject",
            .pairNewMac: "Pair New Mac",
            .pairingCode: "Confirmation code: %@",
            .pairingHint: "Confirm that the same code appears on both Macs.",
            .forgetDevice: "Forget",
            .resetPairings: "Reset All Pairings",
            .alwaysTrustDevice: "Always trust this device",
            .remotePairingChoice: "Click on only one Mac. HangulSync searches automatically. If it is not found, create or enter an invite code.",
            .createInvite: "Create Invite",
            .enterInvite: "Enter Invite",
            .cancel: "Cancel",
            .nearbyPairing: "Nearby Mac",
            .copyInvite: "Copy",
            .pasteInvite: "Paste",
            .invitePlaceholder: "Paste the invite code here",
            .inviteReady: "Pairing Invite Ready",
            .inviteCopied: "The one-time invite was copied. Paste it on the other Mac within 2 minutes.",
            .enterInviteBody: "Paste the invite created on the other Mac.",
            .join: "Connect",
            .invalidInvite: "This invite is invalid or has expired.",
            .updateAvailable: "Update to %@ available…",
            .statusNotConnected: "No Macs connected — click Pair New Mac to connect",
            .viaLocalNetwork: "local network",
            .viaTailscale: "Tailscale",
            .viaIncoming: "incoming",
            .noPeers: "No Macs found yet",
            .tagline: "Fixes Hangul jamo separation over remote desktop.\nInput state syncs automatically between Macs.",
            .statusSyncing: "Active — Korean/English switching is synced with connected Macs",
            .statusStandby: "Standby — activates automatically when a remote desktop app is running",
            .statusPaused: "Paused",
            .dockHint: "You can reopen Settings from the menu bar icon.",
            .settings: "Settings…",
            .showInDock: "Show Icon in Dock",
            .onlyDuringRemote: "Sync Only During Remote Sessions",
            .connectedMacs: "Connected Macs: %d",
            .pauseSync: "Pause Syncing",
            .resumeSync: "Resume Syncing",
            .launchAtLogin: "Launch at Login",
            .quit: "Quit",
            .loginErrorTitle: "Failed to enable Launch at Login",
            .loginErrorBody: "Move the app to the /Applications folder and try again.",
        ],
        "ko": [
            .connectionRequest: "HangulSync 연결 요청",
            .connectionRequestBody: "%@에서 입력 소스 동기화를 요청했습니다. 이 연결을 신뢰합니까?",
            .approve: "승인",
            .reject: "거부",
            .pairNewMac: "새 Mac 페어링",
            .pairingCode: "확인 코드: %@",
            .pairingHint: "두 Mac에 같은 코드가 표시되는지 확인하세요.",
            .forgetDevice: "기기 삭제",
            .resetPairings: "모든 페어링 초기화",
            .alwaysTrustDevice: "이 기기를 계속 신뢰",
            .remotePairingChoice: "한쪽 Mac에서만 누르면 됩니다. 기기를 자동으로 찾고 있으며, 찾지 못하면 초대 코드를 만들거나 입력하세요.",
            .createInvite: "초대 코드 만들기",
            .enterInvite: "초대 코드 입력",
            .cancel: "취소",
            .nearbyPairing: "자동 연결 / Tailscale",
            .copyInvite: "복사",
            .pasteInvite: "붙여넣기",
            .invitePlaceholder: "초대 코드를 여기에 붙여 넣으세요",
            .inviteReady: "페어링 초대 준비됨",
            .inviteCopied: "일회용 초대 코드가 복사되었습니다. 2분 안에 다른 Mac에 붙여 넣으세요.",
            .enterInviteBody: "다른 Mac에서 만든 초대 코드를 붙여 넣으세요.",
            .join: "연결",
            .invalidInvite: "초대 코드가 잘못되었거나 만료되었습니다.",
            .updateAvailable: "새 버전 %@ 업데이트…",
            .statusNotConnected: "연결된 Mac 없음 — 새 Mac 페어링을 눌러 연결하세요",
            .viaLocalNetwork: "같은 네트워크",
            .viaTailscale: "Tailscale",
            .viaIncoming: "수신 연결",
            .noPeers: "아직 발견된 Mac 없음",
            .tagline: "원격 데스크탑 연결 시 한글 자소 분리를 해결합니다.\n한·영 입력 상태가 Mac 간 자동으로 동기화됩니다.",
            .statusSyncing: "작동 중 — 연결된 Mac과 한·영 전환이 동기화됩니다",
            .statusStandby: "대기 중 — 원격 데스크탑 앱을 실행하면 자동으로 작동합니다",
            .statusPaused: "일시정지됨",
            .dockHint: "숨겨도 메뉴바 아이콘으로 설정을 열 수 있어요.",
            .settings: "설정…",
            .showInDock: "Dock에 아이콘 표시",
            .onlyDuringRemote: "원격 접속 중에만 동기화",
            .connectedMacs: "연결된 Mac: %d대",
            .pauseSync: "동기화 일시정지",
            .resumeSync: "동기화 재개",
            .launchAtLogin: "로그인 시 자동 실행",
            .quit: "종료",
            .loginErrorTitle: "자동 실행 설정 실패",
            .loginErrorBody: "앱을 /Applications 폴더로 옮긴 뒤 다시 시도해 주세요.",
        ],
        "ja": [
            .alwaysTrustDevice: "このデバイスを常に信頼する",
            .remotePairingChoice: "片方の Mac でのみ押してください。自動検索で見つからない場合は、招待コードを作成または入力します。",
            .createInvite: "招待コードを作成",
            .enterInvite: "招待コードを入力",
            .cancel: "キャンセル",
            .nearbyPairing: "近くの Mac",
            .copyInvite: "コピー",
            .pasteInvite: "貼り付け",
            .invitePlaceholder: "招待コードをここに貼り付け",
            .inviteReady: "ペアリング招待の準備完了",
            .inviteCopied: "一回限りの招待コードをコピーしました。2分以内にもう一方の Mac に貼り付けてください。",
            .enterInviteBody: "もう一方の Mac で作成した招待コードを貼り付けてください。",
            .join: "接続",
            .invalidInvite: "招待コードが無効か、期限切れです。",
            .pairNewMac: "新しい Mac をペアリング",
            .pairingCode: "確認コード: %@",
            .pairingHint: "両方の Mac に同じコードが表示されていることを確認してください。",
            .forgetDevice: "削除",
            .resetPairings: "すべてのペアリングをリセット",
            .updateAvailable: "新バージョン %@ にアップデート…",
            .statusNotConnected: "接続中の Mac なし — 新しい Mac をペアリングしてください",
            .viaLocalNetwork: "同一ネットワーク",
            .viaTailscale: "Tailscale",
            .viaIncoming: "受信接続",
            .noPeers: "まだ Mac が見つかりません",
            .tagline: "リモート接続時のハングル字母分離を解決。\n入力状態が Mac 間で自動的に同期されます。",
            .statusSyncing: "作動中 — 接続中の Mac と入力切替が同期されています",
            .statusStandby: "待機中 — リモートデスクトップアプリを実行すると自動で作動します",
            .statusPaused: "一時停止中",
            .dockHint: "隠してもメニューバーから設定を開けます。",
            .settings: "設定…",
            .showInDock: "Dockにアイコンを表示",
            .onlyDuringRemote: "リモート接続中のみ同期",
            .connectedMacs: "接続中のMac: %d台",
            .pauseSync: "同期を一時停止",
            .resumeSync: "同期を再開",
            .launchAtLogin: "ログイン時に自動起動",
            .quit: "終了",
            .loginErrorTitle: "自動起動の設定に失敗しました",
            .loginErrorBody: "アプリを /Applications フォルダに移動してからもう一度お試しください。",
        ],
        "zh-Hans": [
            .alwaysTrustDevice: "始终信任此设备",
            .remotePairingChoice: "只需在一台 Mac 上点击。应用会自动查找设备，找不到时再创建或输入邀请码。",
            .createInvite: "创建邀请码",
            .enterInvite: "输入邀请码",
            .cancel: "取消",
            .nearbyPairing: "附近的 Mac",
            .copyInvite: "复制",
            .pasteInvite: "粘贴",
            .invitePlaceholder: "在此粘贴邀请码",
            .inviteReady: "配对邀请已准备",
            .inviteCopied: "一次性邀请码已复制。请在 2 分钟内粘贴到另一台 Mac。",
            .enterInviteBody: "粘贴另一台 Mac 创建的邀请码。",
            .join: "连接",
            .invalidInvite: "邀请码无效或已过期。",
            .pairNewMac: "配对新 Mac",
            .pairingCode: "确认代码：%@",
            .pairingHint: "请确认两台 Mac 显示相同的代码。",
            .forgetDevice: "删除",
            .resetPairings: "重置所有配对",
            .updateAvailable: "有新版本 %@,点击更新…",
            .statusNotConnected: "没有已连接的 Mac — 请点击配对新 Mac",
            .viaLocalNetwork: "同一网络",
            .viaTailscale: "Tailscale",
            .viaIncoming: "传入连接",
            .noPeers: "尚未发现 Mac",
            .tagline: "解决远程桌面导致的韩文字母分离问题。\n输入状态在 Mac 之间自动同步。",
            .statusSyncing: "运行中 — 正在与已连接的 Mac 同步输入切换",
            .statusStandby: "待机 — 运行远程桌面应用时自动开始工作",
            .statusPaused: "已暂停",
            .dockHint: "隐藏后仍可从菜单栏图标打开设置。",
            .settings: "设置…",
            .showInDock: "在程序坞中显示图标",
            .onlyDuringRemote: "仅在远程会话期间同步",
            .connectedMacs: "已连接的 Mac:%d 台",
            .pauseSync: "暂停同步",
            .resumeSync: "恢复同步",
            .launchAtLogin: "登录时自动启动",
            .quit: "退出",
            .loginErrorTitle: "自动启动设置失败",
            .loginErrorBody: "请将应用移动到 /Applications 文件夹后重试。",
        ],
        "zh-Hant": [
            .alwaysTrustDevice: "永遠信任此裝置",
            .remotePairingChoice: "只需在一台 Mac 上按下。應用程式會自動尋找裝置，找不到時再建立或輸入邀請碼。",
            .createInvite: "建立邀請碼",
            .enterInvite: "輸入邀請碼",
            .cancel: "取消",
            .nearbyPairing: "附近的 Mac",
            .copyInvite: "複製",
            .pasteInvite: "貼上",
            .invitePlaceholder: "在此貼上邀請碼",
            .inviteReady: "配對邀請已準備",
            .inviteCopied: "一次性邀請碼已複製。請在 2 分鐘內貼到另一台 Mac。",
            .enterInviteBody: "貼上另一台 Mac 建立的邀請碼。",
            .join: "連線",
            .invalidInvite: "邀請碼無效或已過期。",
            .pairNewMac: "配對新的 Mac",
            .pairingCode: "確認碼：%@",
            .pairingHint: "請確認兩台 Mac 顯示相同的代碼。",
            .forgetDevice: "刪除",
            .resetPairings: "重設所有配對",
            .updateAvailable: "有新版本 %@,點擊更新…",
            .statusNotConnected: "沒有已連接的 Mac — 請按下配對新的 Mac",
            .viaLocalNetwork: "同一網路",
            .viaTailscale: "Tailscale",
            .viaIncoming: "傳入連線",
            .noPeers: "尚未發現 Mac",
            .tagline: "解決遠端桌面導致的韓文字母分離問題。\n輸入狀態在 Mac 之間自動同步。",
            .statusSyncing: "運作中 — 正在與已連接的 Mac 同步輸入切換",
            .statusStandby: "待機 — 執行遠端桌面應用時自動開始運作",
            .statusPaused: "已暫停",
            .dockHint: "隱藏後仍可從選單列圖示開啟設定。",
            .settings: "設定…",
            .showInDock: "在 Dock 中顯示圖示",
            .onlyDuringRemote: "僅在遠端工作階段期間同步",
            .connectedMacs: "已連接的 Mac:%d 台",
            .pauseSync: "暫停同步",
            .resumeSync: "繼續同步",
            .launchAtLogin: "登入時自動啟動",
            .quit: "結束",
            .loginErrorTitle: "自動啟動設定失敗",
            .loginErrorBody: "請將應用程式移至 /Applications 資料夾後再試一次。",
        ],
        "th": [
            .alwaysTrustDevice: "เชื่อถืออุปกรณ์นี้เสมอ",
            .remotePairingChoice: "กดบน Mac เพียงเครื่องเดียว ระบบจะค้นหาอัตโนมัติ หากไม่พบให้สร้างหรือกรอกรหัสเชิญ",
            .createInvite: "สร้างรหัสเชิญ",
            .enterInvite: "กรอกรหัสเชิญ",
            .cancel: "ยกเลิก",
            .nearbyPairing: "Mac ที่อยู่ใกล้",
            .copyInvite: "คัดลอก",
            .pasteInvite: "วาง",
            .invitePlaceholder: "วางรหัสเชิญที่นี่",
            .inviteReady: "รหัสเชิญพร้อมแล้ว",
            .inviteCopied: "คัดลอกรหัสเชิญแบบใช้ครั้งเดียวแล้ว กรุณาวางบน Mac อีกเครื่องภายใน 2 นาที",
            .enterInviteBody: "วางรหัสเชิญที่สร้างจาก Mac อีกเครื่อง",
            .join: "เชื่อมต่อ",
            .invalidInvite: "รหัสเชิญไม่ถูกต้องหรือหมดอายุแล้ว",
            .pairNewMac: "จับคู่ Mac เครื่องใหม่",
            .pairingCode: "รหัสยืนยัน: %@",
            .pairingHint: "ตรวจสอบว่า Mac ทั้งสองเครื่องแสดงรหัสเดียวกัน",
            .forgetDevice: "ลบ",
            .resetPairings: "รีเซ็ตการจับคู่ทั้งหมด",
            .updateAvailable: "มีเวอร์ชันใหม่ %@ อัปเดต…",
            .statusNotConnected: "ไม่มี Mac ที่เชื่อมต่อ — กดจับคู่ Mac เครื่องใหม่",
            .viaLocalNetwork: "เครือข่ายเดียวกัน",
            .viaTailscale: "Tailscale",
            .viaIncoming: "การเชื่อมต่อขาเข้า",
            .noPeers: "ยังไม่พบเครื่อง Mac",
            .tagline: "แก้ปัญหาตัวอักษรเกาหลีแตกจากรีโมตเดสก์ท็อป\nสถานะการป้อนซิงค์ระหว่าง Mac โดยอัตโนมัติ",
            .statusSyncing: "กำลังทำงาน — ซิงค์การสลับภาษากับ Mac ที่เชื่อมต่อ",
            .statusStandby: "สแตนด์บาย — จะทำงานอัตโนมัติเมื่อเปิดแอปรีโมตเดสก์ท็อป",
            .statusPaused: "หยุดชั่วคราว",
            .dockHint: "ซ่อนแล้วก็ยังเปิดการตั้งค่าจากเมนูบาร์ได้",
            .settings: "การตั้งค่า…",
            .showInDock: "แสดงไอคอนใน Dock",
            .onlyDuringRemote: "ซิงค์เฉพาะระหว่างการเชื่อมต่อระยะไกล",
            .connectedMacs: "Mac ที่เชื่อมต่อ: %d เครื่อง",
            .pauseSync: "หยุดการซิงค์ชั่วคราว",
            .resumeSync: "ทำการซิงค์ต่อ",
            .launchAtLogin: "เปิดอัตโนมัติเมื่อเข้าสู่ระบบ",
            .quit: "ออก",
            .loginErrorTitle: "ตั้งค่าเปิดอัตโนมัติไม่สำเร็จ",
            .loginErrorBody: "ย้ายแอปไปยังโฟลเดอร์ /Applications แล้วลองอีกครั้ง",
        ],
        "ru": [
            .alwaysTrustDevice: "Всегда доверять этому устройству",
            .remotePairingChoice: "Нажмите только на одном Mac. Поиск выполняется автоматически; если устройство не найдено, создайте или введите приглашение.",
            .createInvite: "Создать приглашение",
            .enterInvite: "Ввести приглашение",
            .cancel: "Отмена",
            .nearbyPairing: "Mac поблизости",
            .copyInvite: "Копировать",
            .pasteInvite: "Вставить",
            .invitePlaceholder: "Вставьте приглашение сюда",
            .inviteReady: "Приглашение готово",
            .inviteCopied: "Одноразовое приглашение скопировано. Вставьте его на другом Mac в течение 2 минут.",
            .enterInviteBody: "Вставьте приглашение, созданное на другом Mac.",
            .join: "Подключить",
            .invalidInvite: "Приглашение неверно или истекло.",
            .pairNewMac: "Подключить новый Mac",
            .pairingCode: "Код подтверждения: %@",
            .pairingHint: "Убедитесь, что на обоих Mac показан одинаковый код.",
            .forgetDevice: "Удалить",
            .resetPairings: "Сбросить все подключения",
            .updateAvailable: "Доступно обновление %@…",
            .statusNotConnected: "Нет подключённых Mac — нажмите Подключить новый Mac",
            .viaLocalNetwork: "локальная сеть",
            .viaTailscale: "Tailscale",
            .viaIncoming: "входящее",
            .noPeers: "Mac пока не найдены",
            .tagline: "Устраняет распад хангыля при удалённом доступе.\nВвод синхронизируется между Mac автоматически.",
            .statusSyncing: "Работает — переключение ввода синхронизируется с подключёнными Mac",
            .statusStandby: "Ожидание — включится автоматически при запуске удалённого рабочего стола",
            .statusPaused: "Приостановлено",
            .dockHint: "Настройки останутся доступны через строку меню.",
            .settings: "Настройки…",
            .showInDock: "Показывать значок в Dock",
            .onlyDuringRemote: "Синхронизировать только во время удалённого сеанса",
            .connectedMacs: "Подключено Mac: %d",
            .pauseSync: "Приостановить синхронизацию",
            .resumeSync: "Возобновить синхронизацию",
            .launchAtLogin: "Запускать при входе",
            .quit: "Выйти",
            .loginErrorTitle: "Не удалось включить автозапуск",
            .loginErrorBody: "Переместите приложение в папку /Applications и повторите попытку.",
        ],
        "it": [
            .alwaysTrustDevice: "Considera sempre attendibile questo dispositivo",
            .remotePairingChoice: "Premi su un solo Mac. La ricerca è automatica; se l'altro Mac non appare, crea o inserisci un invito.",
            .createInvite: "Crea invito",
            .enterInvite: "Inserisci invito",
            .cancel: "Annulla",
            .nearbyPairing: "Mac vicino",
            .copyInvite: "Copia",
            .pasteInvite: "Incolla",
            .invitePlaceholder: "Incolla qui l'invito",
            .inviteReady: "Invito pronto",
            .inviteCopied: "L'invito monouso è stato copiato. Incollalo sull'altro Mac entro 2 minuti.",
            .enterInviteBody: "Incolla l'invito creato sull'altro Mac.",
            .join: "Connetti",
            .invalidInvite: "L'invito non è valido o è scaduto.",
            .pairNewMac: "Abbina un nuovo Mac",
            .pairingCode: "Codice di conferma: %@",
            .pairingHint: "Verifica che lo stesso codice appaia su entrambi i Mac.",
            .forgetDevice: "Rimuovi",
            .resetPairings: "Reimposta tutti gli abbinamenti",
            .updateAvailable: "Aggiornamento %@ disponibile…",
            .statusNotConnected: "Nessun Mac connesso — premi Abbina un nuovo Mac",
            .viaLocalNetwork: "rete locale",
            .viaTailscale: "Tailscale",
            .viaIncoming: "in entrata",
            .noPeers: "Nessun Mac trovato",
            .tagline: "Risolve i jamo separati nel desktop remoto.\nL'input si sincronizza automaticamente tra i Mac.",
            .statusSyncing: "Attivo — il cambio di lingua è sincronizzato con i Mac connessi",
            .statusStandby: "In attesa — si attiva automaticamente quando è in esecuzione un'app di desktop remoto",
            .statusPaused: "In pausa",
            .dockHint: "Le Impostazioni restano accessibili dalla barra dei menu.",
            .settings: "Impostazioni…",
            .showInDock: "Mostra icona nel Dock",
            .onlyDuringRemote: "Sincronizza solo durante le sessioni remote",
            .connectedMacs: "Mac connessi: %d",
            .pauseSync: "Sospendi sincronizzazione",
            .resumeSync: "Riprendi sincronizzazione",
            .launchAtLogin: "Avvia al login",
            .quit: "Esci",
            .loginErrorTitle: "Impossibile attivare l'avvio al login",
            .loginErrorBody: "Sposta l'app nella cartella /Applications e riprova.",
        ],
    ]
}
